services:
  - type: web
    name: lavalust-product-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: DB_DRIVER
        value: pdo
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_KEY
        generateValue: true
      - key: ALLOW_ORIGIN
        value: "*"
